name: Build, Tag, and Publish Docker Image with Versioning

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  push:
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN2025 }}

      # Step 3: Set Version to Today's Date
      - name: Set Version
        run: |
          TODAY=$(date +'%d%m%Y')
          echo "VERSION=$TODAY" >> $GITHUB_ENV
          echo "Set version to today's date: $TODAY"

      # Step 4: Build and Push Docker Image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Docker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/back3nd:${{ env.VERSION }}
